# This file is for local development.
# For jekyll-inpsyde-theme's GitHub Pages, use the docs/_config.yml

# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Inpsyde Jekyll Theme
description: A Jekyll theme for Inpsyde package/plugin documentation
baseurl: "/jekyll-inpsyde-theme" # the subpath of your site, e.g. /blog

# Aux links for the upper right navigation
aux_links:
  "Inpsyde Jekyll Theme on GitHub":
    - "https://github.com/inpsyde/jekyll-inpsyde-theme"

# Footer "Edit this page on GitHub" link text
gh_edit_repository: https://github.com/inpsyde/jekyll-inpsyde-theme # the GitHub URL for the repo
gh_edit_branch: master # the default branch of the repo. Default: main

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

permalink: pretty

exclude:
  # Comment out the following line for local development
  - "docs/tests/"

  - "node_modules/"
  - "*.gemspec"
  - "*.gem"
  - "Gemfile"
  - "Gemfile.lock"
  - "package.json"
  - "package-lock.json"
  -  "script/"
  - "LICENSE.txt"
  - "lib/"
  - "bin/"
  - "README.md"
  - "Rakefile"
  - "vendor/"

# Regression tests
# By default, the pages in /docs/tests are excluded when the ste is built.
# To include them, comment-out the relevant line above.
# Uncommenting the following line doesn't work - see https://github.com/jekyll/jekyll/issues/4791
# include: ["docs/tests/"]
