# This file is for local development.
# For generating inpsyde.github.io/jekyll-inpsyde-theme on GitHub Pages, use `docs/_config.yml`.
# Note that on local development, both files will be merged.
# This file overrides config in `docs/_config.yml`.

# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

exclude:
  # Comment out the following line for local development
  - "docs/tests/"

  - "node_modules/"
  - "*.gemspec"
  - "*.gem"
  - "Gemfile"
  - "Gemfile.lock"
  - "package.json"
  - "package-lock.json"
  -  "script/"
  - "LICENSE.txt"
  - "lib/"
  - "bin/"
  - "README.md"
  - "Rakefile"
  - "vendor/"

# Regression tests
# By default, the pages in /docs/tests are excluded when the ste is built.
# To include them, comment-out the relevant line above.
#
# Uncommenting the following line doesn't work. See https://github.com/jekyll/jekyll/issues/4791
# This is fixed in Jekyll v4.0.0.pre.alpha1. See: https://github.com/jekyll/jekyll/pull/7188
#
# include: ["docs/tests/"]

# Overrides `remote_theme` in `docs/_config.yml`.
# Make Jekyll to use this repo as *the theme*.
remote_theme: false
