# This file is for jekyll-inpsyde-theme's GitHub Pages.
# For local development, use the _config.yml file at repo root.

title: Inpsyde Jekyll Theme
description: A Jekyll theme for Inpsyde package/plugin documentation
baseurl: "/jekyll-inpsyde-theme" # the subpath of your site, e.g. /blog

# Aux links for the upper right navigation
aux_links:
  "Inpsyde Jekyll Theme on GitHub":
    - "https://github.com/inpsyde/jekyll-inpsyde-theme"

# Footer "Edit this page on GitHub" link text
gh_edit_repository: https://github.com/inpsyde/assets # the GitHub URL for the repo

# Everything above is repo specific.

###############################################################

# This section is repo specific. These can be omitted if defaults make sense.

# TODO: Change to `master` when merging
gh_edit_branch: master # the default branch of the repo. Default: main
gh_edit_source: docs # the directory containing the docs. Default: docs

###############################################################

# Everything below should be copy and pasted into package repos

## TODO: Change to inpsyde/jekyll-inpsyde-theme
remote_theme: pmarsceill/just-the-docs

###############################################################

# Everything below should be copy and pasted into package repos
# To be replaced by jekyll-inpsyde-theme's `_config.yml` when GitHub Pages supports Jekyll v4.

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

permalink: pretty