# This file is for generating inpsyde.github.io/jekyll-syde-theme on GitHub Pages.
# For local development, use `_config.yml` at repo root.

title: Syde Jekyll Theme
description: A Jekyll theme for Syde package/plugin documentation
baseurl: /jekyll-syde-theme # Your repo name with a leading slash.

# Aux links for the upper right navigation
aux_links:
  "Syde Jekyll Theme on GitHub":
    - https://github.com/inpsyde/jekyll-syde-theme

# Footer "Edit this page on GitHub" link text
gh_edit_repository: https://github.com/inpsyde/jekyll-syde-theme # Your repo GitHub URL

# Everything above is repo specific.

###############################################################

# This section is repo specific. These can be omitted if defaults make sense.

gh_edit_branch: master # The default branch of the repo. Default: main
gh_edit_source: docs # The directory containing the docs. Default: docs

exclude:
  - "tests/" # This is jekyll-syde-theme specific!

###############################################################

# Everything below should be copy and pasted into package repos

remote_theme: inpsyde/jekyll-syde-theme

###############################################################

# Everything below should be copy and pasted into package repos
# To be replaced by jekyll-syde-theme's `_config.yml` when GitHub Pages supports Jekyll v4.

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

permalink: pretty
